export const TRAER_TODOS = 'PUBLICACIONES_FETCH_POSTS';
export const LOADING = 'PUBLICACIONES_LOADING';
export const ERROR = 'PUBLICACIONES_ERROR';
export const TRAER_POR_USUARIO = 'TRAER_POR_USUARIO';
export const ACTUALIZAR = 'ACTUALIZAR';
export const COMENTARIOS_ERROR = 'COMENTARIOS_ERROR';
export const COMENTARIO_LOADING = 'COMENTARIO_CARGANDO';
export const COMENTARIOS_ACTUALIZAR = 'COMENTARIOS_ACTUALIZAR';