export const TRAER_TODOS = 'PUBLICACIONES_FETCH_POSTS';
export const LOADING = 'PUBLICACIONES_LOADING';
export const ERROR = 'PUBLICACIONES_ERROR';
export const TRAER_POR_USUARIO = 'TRAER_POR_USUARIO'